# Generated by Django 2.2 on 2021-03-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profiefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfieFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
